name: Move issued assigned to specific team members to their boards

on:
    issues:
        types: [assigned]

jobs:
    web-app-team:
        runs-on: ubuntu-latest
        if: |
            contains(github.event.issue.assignees.*.login, 't3chguy') ||
            contains(github.event.issue.assignees.*.login, 'andybalaam')
        steps:
            - uses: octokit/graphql-action@v2.x
              id: add_to_project
              with:
                  headers: '{"GraphQL-Features": "projects_next_graphql"}'
                  query: |
                      mutation add_to_project($projectid:ID!,$contentid:ID!) {
                        addProjectV2ItemById(input: {projectId: $projectid contentId: $contentid}) {
                          item {
                            id
                            }
                          }
                        }
                  projectid: ${{ env.PROJECT_ID }}
                  contentid: ${{ github.event.issue.node_id }}
              env:
                  PROJECT_ID: "PVT_kwDOAM0swc4AKjJS"
                  GITHUB_TOKEN: ${{ secrets.ELEMENT_BOT_TOKEN }}
