# This is a tchap-specific file, inspired from the one in matrix-react-sdk
name: Cypress End to End Tests
# Run this job when the "Build" job completes
on:
    workflow_run:
        workflows: ["Build"]
        types:
            - completed
env:
    # Removing this makes the job break.
    REPOSITORY: ${{ github.repository }}
    PR_NUMBER: ${{ github.event.pull_request.number }}
jobs:
    cypress:
        name: Cypress
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Get Node Version
              id: node_version
              run: echo ::set-output name=node_version::$(node -e 'console.log(require("./package.json").engines.node)')
            - name: Yarn cache
              uses: actions/setup-node@v3
              with:
                  cache: "yarn"
                  node-version: ${{ steps.node_version.outputs.node_version }}

            - name: Download build from artifact
              uses: actions/download-artifact@v3
              with:
                  name: devbuild
                  path: webapp

            - name: Run Cypress tests
              uses: cypress-io/github-action@v6.5.0
              with:
                  install: false # disable the default install, we already installed and built.

                  # Serve with 'npx serve', a simple static webserver, so that it starts quickly. The dev server is slow and messy to start.
                  start: "npx serve -p 8080 -L webapp"
                  # Note : 'wait-on' caused issues where localhost was not found by cypress. Be careful if you want to use it.

                  # From matrix-react-sdk : The built-in Electron runner seems to grind to a halt trying
                  # to run the tests, so use chrome.
                  browser: chrome
                  # headed: true # tchap uses headless, since we don't record videos.

                  command: "yarn test:cypress"
                  # Note : 'working-directory' changes pwd, for everything. If you use it you need to change relative paths for everything, it's tricky.
              env:
                  E2E_TEST_USER_EMAIL: ${{ secrets.E2E_TEST_USER_EMAIL }}
                  E2E_TEST_USER_PASSWORD: ${{ secrets.E2E_TEST_USER_PASSWORD }}
                  E2E_TEST_USER_SECURITY_KEY: ${{ secrets.E2E_TEST_USER_SECURITY_KEY }}
                  E2E_TEST_USER_HOMESERVER_URL: "https://matrix.agent1.tchap.incubateur.net"
                  E2E_TEST_USER_HOMESERVER_SHORT: "agent1.tchap.incubateur.net"
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # don't remember what this is for, can't hurt
