#Run the tests
#tchap modification : use "./scripts/install-yarn-linked-repositories.sh" instead of "./scripts/layered.sh"
name: Tests
on:
  pull_request: { }
  push:
    branches: [ develop, master ]
  repository_dispatch:
    types: [ element-web-notify ]
env:
  # These must be set for fetchdep.sh to get the right branch
  REPOSITORY: ${{ github.repository }}
  PR_NUMBER: ${{ github.event.pull_request.number }}
jobs:
  jest:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Yarn cache
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: 16

      - name: Install Dependencies
        run: "./scripts/install-yarn-linked-repositories.sh"

      - name: Run tests with coverage
        run: "yarn coverage --ci"

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: |
            coverage
            !coverage/lcov-report